### ISSUE TITLE
Hi~Need some help with RBioFormats installation problem~

### ISSUE THREAD

**Issue by youkefan18** [aoles/RBioFormats#3]
Dear Andrzej Oleś
 
   I tried to install RBioFormats by running "devtools::install_github("aoles/RBioFormats")", however, it failed with this error:
Makevars.win:1: *** missing separator.  Stop.
Warning: running command 'make -f "Makevars.win" -f "E:/Software/R-32~1.0/etc/x64/Makeconf" -f "E:/Software/R-32~1.0/share/make/winshlib.mk" SHLIB="RBioFormats.dll" WIN=64 TCLBIN=64 OBJECTS="dummy.o"' had status 2
ERROR: compilation failed for package 'RBioFormats'
sessionInfo():
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
###############################################
  What could be the cause? Many thanks in advance!

Sincerely
Fred

**Comment by aoles** [comment]
Hi Fred,
thank you for reporting this! The problem was caused by a Makefile which was originally supposed to compile the Java code during package installation. However, this is actually not necessary as I already provide the compiled .jar file with the package.

I've fixed this by removing the obsolete src/ directory from package sources. Please let me know whether this helped.
Andrzej

**Comment by youkefan18** [comment]
Dear Andrzej

   Thank you so much for your great help~~Have a good day sir~

Cheers
Fred
