### ISSUE TITLE
Load RBioFormats with an older version of bioformats?

### ISSUE THREAD

**Issue by gvogler** [aoles/RBioFormats#43]
Hi!

I don't seem to understand where RBioFormats determines which version of Bioformats it is using. Is it always the most current? How would I supply a version number to be used instead?

**Comment by aoles** [comment]
Hi,
Bio-Formats library version is tied to a specific RBioFormats package version through an entry in the DESCRIPTION file. To use an older version of the library you would need to install an older version of the package. Package versions corresponding to different Bio-Formats library versions are tagged, see the [list of tags](https://github.com/aoles/RBioFormats/tags). For example, in order to install the version of the package running against Bio-Formats 6.14.0 you could use the following command.

```r
BiocManager::install("aoles/RBioFormats@Bio-Formats_6.14.0")
```
